// ═══════════════════════════════════════════════════════════════════
// Signal pattern databases — 200+ patterns across 8 categories
// ═══════════════════════════════════════════════════════════════════

export interface PatternEntry {
  pattern: string;
  weight: number;
}

// ── EMOTIONAL / MANIPULATIVE LANGUAGE ─────────────────────────────
export const emotionalPatterns: PatternEntry[] = [
  { pattern: "shocking", weight: 0.8 },
  { pattern: "unbelievable", weight: 0.85 },
  { pattern: "you won't believe", weight: 0.95 },
  { pattern: "mind-blowing", weight: 0.8 },
  { pattern: "terrifying", weight: 0.65 },
  { pattern: "outrage", weight: 0.6 },
  { pattern: "destroy", weight: 0.45 },
  { pattern: "catastrophe", weight: 0.5 },
  { pattern: "jaw-dropping", weight: 0.75 },
  { pattern: "horrifying", weight: 0.7 },
  { pattern: "disgusting", weight: 0.6 },
  { pattern: "insane", weight: 0.55 },
  { pattern: "nightmare", weight: 0.5 },
  { pattern: "devastating", weight: 0.45 },
  { pattern: "bombshell", weight: 0.7 },
  { pattern: "explosive", weight: 0.55 },
  { pattern: "earth-shattering", weight: 0.8 },
  { pattern: "panic", weight: 0.5 },
  { pattern: "furious", weight: 0.45 },
  { pattern: "enraged", weight: 0.5 },
  { pattern: "heartbreaking", weight: 0.35 },
  { pattern: "blood boiling", weight: 0.7 },
  { pattern: "makes you sick", weight: 0.65 },
  { pattern: "will blow your mind", weight: 0.85 },
  { pattern: "left speechless", weight: 0.6 },
  { pattern: "absolutely incredible", weight: 0.5 },
  { pattern: "total disaster", weight: 0.55 },
  { pattern: "pure evil", weight: 0.7 },
  { pattern: "monster", weight: 0.4 },
  { pattern: "traitor", weight: 0.55 },
];

// ── CLICKBAIT / URGENCY ───────────────────────────────────────────
export const clickbaitPatterns: PatternEntry[] = [
  { pattern: "share before deleted", weight: 0.95 },
  { pattern: "share before they delete", weight: 0.95 },
  { pattern: "going viral", weight: 0.6 },
  { pattern: "act now", weight: 0.7 },
  { pattern: "limited time", weight: 0.6 },
  { pattern: "urgent", weight: 0.45 },
  { pattern: "breaking", weight: 0.35 },
  { pattern: "exclusive", weight: 0.35 },
  { pattern: "you need to see this", weight: 0.8 },
  { pattern: "watch before removed", weight: 0.9 },
  { pattern: "this changes everything", weight: 0.7 },
  { pattern: "what happens next", weight: 0.5 },
  { pattern: "number 5 will shock", weight: 0.9 },
  { pattern: "won't believe what", weight: 0.85 },
  { pattern: "click here", weight: 0.6 },
  { pattern: "don't miss", weight: 0.4 },
  { pattern: "last chance", weight: 0.55 },
  { pattern: "spread the word", weight: 0.5 },
  { pattern: "share this now", weight: 0.6 },
  { pattern: "repost", weight: 0.3 },
  { pattern: "must read", weight: 0.4 },
  { pattern: "must watch", weight: 0.5 },
  { pattern: "gone wrong", weight: 0.45 },
  { pattern: "you'll never guess", weight: 0.75 },
  { pattern: "the reason will shock", weight: 0.85 },
  { pattern: "see what happened", weight: 0.4 },
  { pattern: "wait until you see", weight: 0.65 },
];

// ── ABSOLUTE / CONSPIRACY CLAIMS ──────────────────────────────────
export const absolutePatterns: PatternEntry[] = [
  { pattern: "100% proof", weight: 0.95 },
  { pattern: "they don't want you to know", weight: 0.98 },
  { pattern: "conspiracy", weight: 0.9 },
  { pattern: "cover-up", weight: 0.85 },
  { pattern: "deep state", weight: 0.95 },
  { pattern: "new world order", weight: 0.95 },
  { pattern: "mainstream media lies", weight: 0.9 },
  { pattern: "wake up", weight: 0.55 },
  { pattern: "open your eyes", weight: 0.8 },
  { pattern: "sheeple", weight: 0.95 },
  { pattern: "miracle cure", weight: 0.95 },
  { pattern: "doctors hate", weight: 0.95 },
  { pattern: "big pharma", weight: 0.8 },
  { pattern: "chemtrails", weight: 0.98 },
  { pattern: "what they're hiding", weight: 0.9 },
  { pattern: "the truth about", weight: 0.6 },
  { pattern: "exposed", weight: 0.5 },
  { pattern: "banned", weight: 0.55 },
  { pattern: "flat earth", weight: 0.98 },
  { pattern: "illuminati", weight: 0.95 },
  { pattern: "false flag", weight: 0.9 },
  { pattern: "crisis actor", weight: 0.95 },
  { pattern: "globalist", weight: 0.7 },
  { pattern: "plandemic", weight: 0.98 },
  { pattern: "microchip", weight: 0.7 },
  { pattern: "5g causes", weight: 0.95 },
  { pattern: "they're lying", weight: 0.75 },
  { pattern: "the elite", weight: 0.6 },
  { pattern: "secret agenda", weight: 0.85 },
  { pattern: "hidden truth", weight: 0.8 },
  { pattern: "suppressed", weight: 0.6 },
  { pattern: "don't trust", weight: 0.5 },
  { pattern: "controlled opposition", weight: 0.85 },
  { pattern: "shadow government", weight: 0.95 },
  { pattern: "puppet master", weight: 0.85 },
  { pattern: "depopulation", weight: 0.85 },
  { pattern: "mind control", weight: 0.9 },
  { pattern: "brainwash", weight: 0.7 },
  { pattern: "propaganda machine", weight: 0.65 },
  { pattern: "mainstream media", weight: 0.5 },
];

// ── MEDICAL / SCIENTIFIC MISINFORMATION ───────────────────────────
export const medicalMisinfo: PatternEntry[] = [
  { pattern: "cures cancer", weight: 0.95 },
  { pattern: "cures diabetes", weight: 0.9 },
  { pattern: "cures alzheimer", weight: 0.95 },
  { pattern: "cures all diseases", weight: 0.98 },
  { pattern: "miracle drug", weight: 0.9 },
  { pattern: "natural remedy", weight: 0.4 },
  { pattern: "big pharma doesn't want", weight: 0.95 },
  { pattern: "vaccine causes autism", weight: 0.98 },
  { pattern: "vaccines are poison", weight: 0.98 },
  { pattern: "anti-vax", weight: 0.7 },
  { pattern: "detox", weight: 0.35 },
  { pattern: "toxins", weight: 0.3 },
  { pattern: "cleanse your body", weight: 0.5 },
  { pattern: "pharmaceutical industry", weight: 0.35 },
  { pattern: "ancient secret", weight: 0.8 },
  { pattern: "one weird trick", weight: 0.9 },
  { pattern: "doctors are baffled", weight: 0.85 },
  { pattern: "the medical establishment", weight: 0.6 },
  { pattern: "suppressed cure", weight: 0.95 },
  { pattern: "heals everything", weight: 0.95 },
  { pattern: "guaranteed results", weight: 0.7 },
  { pattern: "100% safe", weight: 0.6 },
  { pattern: "no side effects", weight: 0.55 },
  { pattern: "fda doesn't want", weight: 0.85 },
  { pattern: "homeopathic", weight: 0.3 },
];

// ── PROPAGANDA / BIAS PATTERNS ────────────────────────────────────
export const propagandaPatterns: PatternEntry[] = [
  { pattern: "every patriot", weight: 0.6 },
  { pattern: "real americans", weight: 0.55 },
  { pattern: "our enemies", weight: 0.5 },
  { pattern: "the left wants", weight: 0.6 },
  { pattern: "the right wants", weight: 0.6 },
  { pattern: "liberals want", weight: 0.55 },
  { pattern: "conservatives want", weight: 0.55 },
  { pattern: "destroying our country", weight: 0.65 },
  { pattern: "fight back", weight: 0.35 },
  { pattern: "us vs them", weight: 0.6 },
  { pattern: "take back our", weight: 0.5 },
  { pattern: "silent majority", weight: 0.45 },
  { pattern: "rigged", weight: 0.55 },
  { pattern: "stolen election", weight: 0.8 },
  { pattern: "voter fraud", weight: 0.5 },
  { pattern: "corrupt officials", weight: 0.45 },
  { pattern: "witch hunt", weight: 0.5 },
  { pattern: "hoax", weight: 0.6 },
  { pattern: "fake news media", weight: 0.7 },
  { pattern: "enemy of the people", weight: 0.75 },
  { pattern: "radical agenda", weight: 0.5 },
  { pattern: "socialist takeover", weight: 0.65 },
  { pattern: "communist", weight: 0.4 },
  { pattern: "fascist", weight: 0.4 },
  { pattern: "tyranny", weight: 0.45 },
];

// ── SOURCE CREDIBILITY SIGNALS (positive) ─────────────────────────
export const credibilityPatterns: PatternEntry[] = [
  { pattern: "according to", weight: 0.7 },
  { pattern: "sources say", weight: 0.4 },
  { pattern: "officials said", weight: 0.7 },
  { pattern: "spokesperson", weight: 0.65 },
  { pattern: "statement released", weight: 0.65 },
  { pattern: "study shows", weight: 0.8 },
  { pattern: "study published", weight: 0.85 },
  { pattern: "research", weight: 0.4 },
  { pattern: "peer-reviewed", weight: 0.95 },
  { pattern: "published in", weight: 0.75 },
  { pattern: "journal of", weight: 0.8 },
  { pattern: "journal", weight: 0.6 },
  { pattern: "university", weight: 0.65 },
  { pattern: "scientists", weight: 0.55 },
  { pattern: "researchers", weight: 0.6 },
  { pattern: "experts", weight: 0.45 },
  { pattern: "evidence", weight: 0.5 },
  { pattern: "findings", weight: 0.55 },
  { pattern: "data", weight: 0.3 },
  { pattern: "statistics", weight: 0.45 },
  { pattern: "report", weight: 0.4 },
  { pattern: "confirmed", weight: 0.45 },
  { pattern: "announced", weight: 0.35 },
  { pattern: "meta-analysis", weight: 0.9 },
  { pattern: "randomized controlled trial", weight: 0.95 },
  { pattern: "double-blind", weight: 0.9 },
  { pattern: "sample size", weight: 0.8 },
  { pattern: "participants", weight: 0.6 },
  { pattern: "methodology", weight: 0.75 },
  { pattern: "controlled study", weight: 0.85 },
  { pattern: "replicated", weight: 0.85 },
  { pattern: "systematic review", weight: 0.9 },
  { pattern: "clinical trial", weight: 0.85 },
  { pattern: "official statement", weight: 0.7 },
  { pattern: "press release", weight: 0.6 },
  { pattern: "fact-check", weight: 0.7 },
  { pattern: "independently verified", weight: 0.85 },
  { pattern: "corroborated", weight: 0.8 },
  { pattern: "documented", weight: 0.55 },
  { pattern: "census", weight: 0.7 },
  { pattern: "government data", weight: 0.65 },
  { pattern: "public record", weight: 0.7 },
  { pattern: "court filing", weight: 0.8 },
  { pattern: "sworn testimony", weight: 0.75 },
  { pattern: "on the record", weight: 0.7 },
  { pattern: "reuters", weight: 0.8 },
  { pattern: "associated press", weight: 0.8 },
  { pattern: "world health organization", weight: 0.75 },
  { pattern: "centers for disease control", weight: 0.8 },
  { pattern: "cdc", weight: 0.6 },
  { pattern: "who", weight: 0.3 },
  { pattern: "fbi", weight: 0.5 },
  { pattern: "nasa", weight: 0.65 },
  { pattern: "national institutes of health", weight: 0.75 },
  { pattern: "united nations", weight: 0.6 },
  { pattern: "european union", weight: 0.55 },
  { pattern: "supreme court", weight: 0.7 },
];

// ── BALANCED REPORTING SIGNALS (positive) ─────────────────────────
export const balancePatterns: PatternEntry[] = [
  { pattern: "however", weight: 0.45 },
  { pattern: "on the other hand", weight: 0.6 },
  { pattern: "critics argue", weight: 0.6 },
  { pattern: "some experts disagree", weight: 0.65 },
  { pattern: "while others", weight: 0.5 },
  { pattern: "it remains unclear", weight: 0.5 },
  { pattern: "could not be independently verified", weight: 0.55 },
  { pattern: "although", weight: 0.35 },
  { pattern: "nevertheless", weight: 0.45 },
  { pattern: "despite", weight: 0.35 },
  { pattern: "opponents say", weight: 0.55 },
  { pattern: "proponents argue", weight: 0.55 },
  { pattern: "both sides", weight: 0.5 },
  { pattern: "remains to be seen", weight: 0.45 },
  { pattern: "further investigation", weight: 0.55 },
  { pattern: "pending review", weight: 0.5 },
  { pattern: "unconfirmed", weight: 0.45 },
  { pattern: "alleged", weight: 0.5 },
  { pattern: "reportedly", weight: 0.4 },
  { pattern: "claims to", weight: 0.35 },
  { pattern: "declined to comment", weight: 0.55 },
  { pattern: "did not respond", weight: 0.45 },
  { pattern: "could not be reached", weight: 0.5 },
  { pattern: "according to both", weight: 0.6 },
  { pattern: "multiple perspectives", weight: 0.65 },
];

// ── OPINION MARKERS ───────────────────────────────────────────────
export const opinionMarkers: string[] = [
  "i think", "i believe", "in my opinion", "clearly", "obviously",
  "everyone knows", "it's clear that", "undeniably", "without question",
  "needless to say", "of course", "surely", "definitely",
  "there's no doubt", "anybody can see", "it goes without saying",
  "common sense tells us", "any reasonable person",
  "it's obvious", "as we all know", "the fact is",
];

// ── KNOWN SATIRE / PARODY INDICATORS ──────────────────────────────
export const satirePatterns: PatternEntry[] = [
  { pattern: "satire", weight: 0.9 },
  { pattern: "parody", weight: 0.9 },
  { pattern: "the onion", weight: 0.95 },
  { pattern: "babylon bee", weight: 0.95 },
  { pattern: "not a real news", weight: 0.9 },
  { pattern: "for entertainment", weight: 0.7 },
  { pattern: "fictional", weight: 0.7 },
  { pattern: "this is humor", weight: 0.8 },
];
